# Generated by Django 2.2.16 on 2021-01-30 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fool', '0005_auto_20210129_1919'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockTicker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('symbol', models.CharField(max_length=7, unique=True)),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('change', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('exchange', models.IntegerField(choices=[(1, 'NASDAQ'), (2, 'NASDAQOTH'), (3, 'NYSE'), (4, 'NYSEMKT'), (5, 'UNKNOWN')])),
                ('sector', models.CharField(choices=[('Financials', 'FINANCIALS'), ('Services', 'SERVICES'), ('Utilities', 'UTILITIES'), ('Basic Materials', 'BASIC_MATERIALS'), ('Sector Equity', 'SECTOR_EQUITY'), ('Technology', 'TECHNOLOGY'), ('Consumer Goods', 'CONSUMER_GOODS')], max_length=100)),
            ],
        ),
    ]
