# Generated by Django 2.2.16 on 2021-01-30 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fool', '0006_stockticker'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'get_latest_by': ['updated_at', 'created_at']},
        ),
        migrations.AlterField(
            model_name='stockticker',
            name='sector',
            field=models.CharField(choices=[('Financials', 'FINANCIALS'), ('Services', 'SERVICES'), ('Utilities', 'UTILITIES'), ('Basic Materials', 'BASIC_MATERIALS'), ('Sector Equity', 'SECTOR_EQUITY'), ('Technology', 'TECHNOLOGY'), ('Consumer Goods', 'CONSUMER_GOODS'), ('', 'NONE')], max_length=100),
        ),
    ]
