# Generated by Django 2.2.16 on 2021-01-30 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fool', '0007_auto_20210130_1652'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'get_latest_by': ['modified']},
        ),
        migrations.AddField(
            model_name='image',
            name='modified',
            field=models.DateTimeField(null=True),
        ),
    ]
