# Generated by Django 2.2.16 on 2021-01-31 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fool', '0009_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='title',
            field=models.CharField(default='Untitled', max_length=60),
        ),
    ]
